#show heading: set text(font: "New Computer Modern Sans")

#set text(font: "New Computer Modern", hyphenate: false)
#set par(justify: true)

#let sans(body) = {
  set text(font: "New Computer Modern Sans")
  body
}

#let eps = sym.epsilon

#let up = math.upright

#grid(columns: (15%, 1fr), align: (right, left), row-gutter: 1em, column-gutter: 1em)[][

= Unrestricted Grammars

Type 0 or unrestricted grammars are the most general class of grammars in the Chomsky hierarchy. This grammar can generate arbitrary recursively enumerable languages.

An unrestricted grammar $G$ is a four-tuple, $G = (Sigma, N, S, P)$ with the symbols having their usual meanings, and $P$ is a finite set of productions of the form $alpha -> beta$, for any $alpha, beta in (N union Sigma)^*$, with $alpha$ containing at least one non terminal symbol.

As usual, $L(G) = {w in Sigma^* | S ->^*_G w}$.


][#sans[Example 1]][
  The following grammar generates the language $L_1 = {a^(2^n) | n >= 0}$:

  $
  S &-> T a U\
  U &-> A U | eps\
  a A &-> A a a\
  T A &-> T\
  T &-> eps
  $

  A derivation of the string $a^8$ using the above grammar is as follows:

  $
  S &-> T a U -> T a A U -> T a A A U -> T a A A A U\
  &-> T A a a A A U -> T A a A a a A U -> T A A a a a a A U \
  &-> T A A a a a A a a U -> T A A a a A a a a a U -> T A A a A  a a a a a a U\
  &-> T A A A a a a a a a a a U ->^* a a a a a a a a 
  $#h(1fr) $square$
][#sans[Example 2]][
  The following grammar generates the language $L_2 = {a^n b^n c^n | n >= 0}$.

  $
  S &->U T\
  U &-> a U b C | eps\
  C b &-> b C\
  C T &-> T c\
  T &-> eps
  $

  For example, the string $a^2 b^2 c^2$ can be derived as:
  $
  S &-> U T -> a U b C T -> a a U b C b C T -> a a b C b C T -> a a b b C C T \
  &-> a a b  b C T c -> a a b b T c c -> a a b b c c
  $
  #h(1fr)$square$
][][
We will now show, that the class of languages generated by Type 0 grammars are exactly the Turing recognisable (recursively enumerable) languages.
  
][
  #sans[Theorem X.1]
][
  _If $L = L(G)$ for some unrestricted grammar $G$, then $L$ is r.e._
][#sans[Proof:]][
  Let us construct a four-tape nondeterministic Turing machine to recognise $L$.

  We can non-deterministically simulate the grammar $G$ and try to derive the string $x$. If we successfully do so, we accept. The first tape contains the input (and is never changed), the second tape contains the sentential form in the derivation process. The third and fourth tape are used to store $alpha$ and $beta$ for the production $alpha -> beta$ being used.

  $M$ on input $x$ first writes $S$ on the second tape, then loops:
  - Non-deterministically choose a position on the second tape.
  - Non-deterministically choose a production rule $alpha -> beta$.
  - Write $alpha$ to tape 3 and $beta$ to tape 4.
  - Compare tape 2 and tape 3 starting from the chosen position in tape 2.
  - If the comparison succeeds, replace $alpha$ with $beta$ in tape 2, shifting the contents if required.
  - Compare tape 1 and tape 2, if they are identical then accept. #h(1fr)$square$
][
  #sans[Theorem X.2]
][
  _If $L$ is r.e., then $L = L(G)$ for some unrestricted grammar $G$._
][#sans[Proof:]][
  Let $M$ be a DTM recognising $L$. WLOG, assume that $M$ uses a right end marker ($tack.l$) as its rightmost non-blank symbol on its tape throughout its working. Also, modify $M$ so that it erases the tape contents when it accepts a string, so that the final accepting configuration is always $tack.r up(t') tack.l$, where $upright(t')$ is the new accepting state.

  $G$ will simulate the working of the Turing machine in reverse. If the following represents the sequence of configurations reached by the TM to accept $x$:

  $ up(s) tack.r x tack.l quad --> quad dots quad --> quad C_i quad --> quad C_j quad --> quad dots quad --> quad tack up(t') tack.l $

  Then, the grammar will derive $x$ by the following derivation:
  $
  S quad --> quad tack up(t') tack.l quad --> quad ... quad --> quad C_j quad --> quad C_i quad --> quad ... quad --> quad up(s) tack x tack.l quad --> quad x
  $

  $M$ could have transitioned from configuration $C_i$ to $C_j$ by a transition:
  - $delta(up(p), a) = (up(q), b, L)$
  $
  dots.c x upright(p) a y dots.c quad --> quad dots.c upright(q) x b y dots.c
  $
  -  or, $delta(up(p), a) = (up(q), b, R)$
  $
  dots.c x upright(p) a y dots.c quad --> quad dots.c x b up(q) y dots.c
  $

  So, we can define our grammar as $G = (Sigma, V = Q union (Gamma without Sigma) union {S}, S, P)$ with production rules
  $
  S quad &-> quad tack t' tack.l\
  s tack quad &-> quad eps\
  tack.r quad &-> quad eps
  $
  For every transition $delta(up(p), a) = (up(q), b, L)$, $forall x in Gamma$,
  $
  up(q) x b -> x up(p) a
  $
  For every transition $delta(up(p), a) = (up(q), b, R)$,
  $
  b up(q) -> up(p) a 
  $

  The equivalence of languages can be shown by induction.
  #h(1fr) $square$

  
]


